name: Daily Post

on:
  schedule:
    - cron: '0 10 * * *'  # каждый день в 10:00 UTC (13:00 по Москве)
  workflow_dispatch:      # чтобы можно было запустить вручную

jobs:
  post:
    runs-on: ubuntu-latest

    steps:
    - name: Клонировать репозиторий
      uses: actions/checkout@v3

    - name: Установить Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'

    - name: Установить зависимости
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Собрать данные
      run: python data_collector.py

    - name: Сгенерировать и опубликовать пост
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHANNEL_ID: ${{ secrets.TELEGRAM_CHANNEL_ID }}
      run: python main.py
